// ============================================================================
// SNAPCHAT ADS LOCAL KNOWLEDGE BASE & PLAYBOOK
// Master reference for Gen Z Reach, Commercials, AR Lenses, and Low CPM Acquisition
// ============================================================================

import { PlatformKnowledgeEntry } from './googleAdsKnowledge';

export const SNAPCHAT_ADS_KNOWLEDGE: PlatformKnowledgeEntry[] = [
  {
    topic: 'Gen Z Attention & 6-Second Commercials',
    category: 'Video Formats',
    summary: 'Snapchat is the primary communication channel for Gen Z and young millennials. Non-skippable 6-second Commercials guarantee 100% video completion.',
    benchmarks: 'Video Completion Rate (VCR): >85% for Commercials. CPMs: $3.50 - $8.00 (substantially cheaper than Meta).',
    goldenRule: 'Front-load branding within the first 1.5 seconds. Never wait until the end of the ad to reveal the product or core benefit.',
    troubleshootingSteps: [
      'Ensure creative uses 9:16 vertical canvas with clear visual subtitles for sound-off viewers.',
      'Check swipe-up CTA placement; avoid lower 20% of screen where user navigation icons sit.',
      'Deploy Snap Pixel CAPI to recover conversions dropped by browser cookie restrictions.',
      'Set bid type to Auto-Bid during the first $500 spend to establish baseline auction clearing prices.'
    ],
    executiveTalkingPoints: [
      'Snapchat offers incremental reach to 18-29 demographics that have abandoned Facebook feeds.',
      'Our sub-$7 CPMs allow us to build massive brand awareness and re-target viewers across search channels.',
      'Gen Z buyers exhibit high brand loyalty when approached with native, non-intrusive short-form video.'
    ]
  },
  {
    topic: 'Augmented Reality (AR) Lens Conversion Architecture',
    category: 'Interactive Media',
    summary: 'AR Lenses allow users to virtually try on sunglasses, makeup, shoes, or interact with 3D product models, driving viral friend-to-friend shares.',
    benchmarks: 'Average Lens Play Time: 12-18 seconds. Share rate: 1 in 5 users share the lens with friends.',
    goldenRule: 'Include a direct "Shop Now" or "Get Offer" button inside the AR experience to capture immediate purchase intent.',
    troubleshootingSteps: [
      'Test 3D asset file size: keep under 4MB for instant loading across older smartphones and LTE networks.',
      'Pair AR Lens campaigns with retargeting Story Ads targeting users who engaged with the lens for >10 seconds.',
      'Verify attribution window matches purchase consideration timeline (typically 7-day swipe + 1-day view).',
      'Track earned impressions generated by organic user shares in Lens Web Builder.'
    ],
    executiveTalkingPoints: [
      'AR bridges the physical-digital divide by placing the product in the customer\'s hands before purchase.',
      'Average dwell time exceeds 15 seconds, creating 5x higher brand recall than static display ads.',
      'Every organic share represents earned media that lowers our blended customer acquisition cost.'
    ]
  }
];
