import { Scenario } from '@/types/scenario';
import { 
  ALL_170_SCENARIOS,
  ALL_MARKETING_SCENARIOS as BASE_170_SCENARIOS,
  BEGINNER_SCENARIOS,
  INTERMEDIATE_SCENARIOS,
  ADVANCED_SCENARIOS,
  LEGEND_SCENARIOS
} from '@/data/marketingScenariosCatalog';
import { 
  CORE_MARKETING_METRICS,
  GITHUB_KNOWLEDGE_ARTICLES
} from '@/data/githubMarketingKnowledgeBase';
import { 
  ALL_AGGREGATED_PLATFORM_SCENARIOS,
  getScenariosForPlatform,
  ALL_PLATFORM_SCENARIOS_MAP
} from '@/data/platformScenarios';

export const ALL_MARKETING_SCENARIOS: Scenario[] = [
  ...ALL_AGGREGATED_PLATFORM_SCENARIOS,
  ...ALL_170_SCENARIOS
];

export {
  ALL_170_SCENARIOS,
  BEGINNER_SCENARIOS,
  INTERMEDIATE_SCENARIOS,
  ADVANCED_SCENARIOS,
  LEGEND_SCENARIOS,
  CORE_MARKETING_METRICS,
  GITHUB_KNOWLEDGE_ARTICLES,
  ALL_AGGREGATED_PLATFORM_SCENARIOS,
  getScenariosForPlatform,
  ALL_PLATFORM_SCENARIOS_MAP
};

// Full multi-platform catalog of scenarios
export const CRISIS_SCENARIOS: Scenario[] = ALL_MARKETING_SCENARIOS;

